CREATE TABLE IF NOT EXISTS public.marketplace_plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  title VARCHAR(255) NOT NULL,
  description TEXT,
  channels TEXT[] NOT NULL,  -- ['amazon','mercadolivre','shopee', etc]

  status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'executing', 'done')),

  plan_data JSONB NOT NULL,  -- {summary, opportunities[], phases[], metrics[]}

  created_by_agent VARCHAR(50),  -- 'nexo', 'scheduler', etc
  created_by_user UUID REFERENCES public.users(id),

  approved_by UUID REFERENCES public.users(id),
  approved_at TIMESTAMP WITH TIME ZONE,
  rejection_reason TEXT,

  is_scheduled BOOLEAN DEFAULT FALSE,  -- true = generated by 7-day scheduler
  scheduled_frequency VARCHAR(20),  -- 'weekly', 'monthly', etc

  phase1_tasks_created BOOLEAN DEFAULT FALSE,
  phase1_created_at TIMESTAMP WITH TIME ZONE,
  phase1_task_ids UUID[] DEFAULT '{}',

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);