-- Migration: Create marketplace_plans table for strategic analysis plans
-- Date: 2026-02-22
-- Description: Stores analysis plans generated by marketplace agents
--              with approval workflow and execution tracking

-- ============================================================================
-- TABLE: marketplace_plans
-- ============================================================================
-- Purpose: Store strategic analysis plans generated by marketplace agents
--          with status tracking and approval workflow
-- RLS: Admins/Heads see all; Executors have no access

CREATE TABLE IF NOT EXISTS public.marketplace_plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Plan metadata
  title VARCHAR(255) NOT NULL,
  description TEXT,
  channels TEXT[] NOT NULL,  -- ['amazon','mercadolivre','shopee', etc]

  -- Status workflow
  status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'executing', 'done')),

  -- Plan content (structured JSON)
  plan_data JSONB NOT NULL,  -- {summary, opportunities[], phases[], metrics[]}

  -- Agent metadata
  created_by_agent VARCHAR(50),  -- 'nexo', 'scheduler', etc
  created_by_user UUID REFERENCES public.users(id),

  -- Approval workflow
  approved_by UUID REFERENCES public.users(id),
  approved_at TIMESTAMP WITH TIME ZONE,
  rejection_reason TEXT,

  -- Scheduler tracking
  is_scheduled BOOLEAN DEFAULT FALSE,  -- true = generated by 7-day scheduler
  scheduled_frequency VARCHAR(20),  -- 'weekly', 'monthly', etc

  -- Phase 1 execution tracking
  phase1_tasks_created BOOLEAN DEFAULT FALSE,
  phase1_created_at TIMESTAMP WITH TIME ZONE,
  phase1_task_ids UUID[] DEFAULT '{}',

  -- Audit
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.marketplace_plans IS 'Strategic analysis plans generated by marketplace agents with approval workflow';
COMMENT ON COLUMN public.marketplace_plans.channels IS 'Array of marketplace channels: amazon, mercadolivre, shopee, shein, tiktok-shop, kaway';
COMMENT ON COLUMN public.marketplace_plans.plan_data IS 'JSONB: {summary, opportunities[], phases[], metrics[]}';
COMMENT ON COLUMN public.marketplace_plans.status IS 'Workflow: pending → approved → executing → done (or rejected)';
COMMENT ON COLUMN public.marketplace_plans.is_scheduled IS 'TRUE if generated by 7-day scheduler, FALSE if manual request';
COMMENT ON COLUMN public.marketplace_plans.phase1_tasks_created IS 'TRUE after createPhase1Tasks() executed on approval';

-- ============================================================================
-- INDEXES
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_marketplace_plans_status ON public.marketplace_plans(status);
CREATE INDEX IF NOT EXISTS idx_marketplace_plans_created_at ON public.marketplace_plans(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_plans_channels ON public.marketplace_plans USING GIN (channels);
CREATE INDEX IF NOT EXISTS idx_marketplace_plans_approved_by ON public.marketplace_plans(approved_by);

-- ============================================================================
-- ENABLE RLS
-- ============================================================================
ALTER TABLE public.marketplace_plans ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES: marketplace_plans
-- ============================================================================
-- Rules:
-- - Admin: sees all plans, can do everything
-- - Head: sees all plans, can approve/reject
-- - Executor: NO access (cannot see or modify)
-- - QA: can view but cannot approve

-- Admin sees all
DROP POLICY IF EXISTS "Admin sees all marketplace plans" ON public.marketplace_plans;
CREATE POLICY "Admin sees all marketplace plans"
  ON public.marketplace_plans FOR SELECT
  USING (auth.jwt()->>'role' = 'admin');

-- Head sees all, can approve/reject
DROP POLICY IF EXISTS "Head sees all marketplace plans" ON public.marketplace_plans;
CREATE POLICY "Head sees all marketplace plans"
  ON public.marketplace_plans FOR SELECT
  USING (auth.jwt()->>'role' IN ('head', 'admin'));

DROP POLICY IF EXISTS "Head can approve/reject plans" ON public.marketplace_plans;
CREATE POLICY "Head can approve/reject plans"
  ON public.marketplace_plans FOR UPDATE
  USING (auth.jwt()->>'role' IN ('head', 'admin'))
  WITH CHECK (
    -- Can only update approval-related fields
    (status IN ('approved', 'rejected') AND (approved_by = auth.uid() OR auth.jwt()->>'role' = 'admin'))
  );

-- Admin can create plans
DROP POLICY IF EXISTS "Admin can create plans" ON public.marketplace_plans;
CREATE POLICY "Admin can create plans"
  ON public.marketplace_plans FOR INSERT
  WITH CHECK (auth.jwt()->>'role' = 'admin');

-- QA can view but not modify
DROP POLICY IF EXISTS "QA can view marketplace plans" ON public.marketplace_plans;
CREATE POLICY "QA can view marketplace plans"
  ON public.marketplace_plans FOR SELECT
  USING (auth.jwt()->>'role' = 'qa');
